# Generated by Django 6.0.2 on 2026-09-23 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_third_fits_priority_slot'),
        ('schedule', '0016_shift_workbook_name_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkbookPromoRows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rows', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workbook_promo_rows', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='WorkbookPromoDayOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField()),
                ('rows', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workbook_promo_day_overrides', to='api.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'business_date'), name='unique_workbook_promo_override_per_org_date')],
            },
        ),
    ]
